// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOOijkatm-JK4d3avjwVn-_GhlWo7qGCI',
    appId: '1:469970791522:web:6eccca868be66dc8bef53b',
    messagingSenderId: '469970791522',
    projectId: 'tictactoe-online-f75da',
    authDomain: 'tictactoe-online-f75da.firebaseapp.com',
    storageBucket: 'tictactoe-online-f75da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9cu681onm92cr86VksOnEnupcRAGZVMU',
    appId: '1:469970791522:android:7c7dfcc8a2bc57ecbef53b',
    messagingSenderId: '469970791522',
    projectId: 'tictactoe-online-f75da',
    storageBucket: 'tictactoe-online-f75da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg67EP_KfAKn03595HjEiBvvCCMLcDRTs',
    appId: '1:469970791522:ios:ee3fe72743b14c11bef53b',
    messagingSenderId: '469970791522',
    projectId: 'tictactoe-online-f75da',
    storageBucket: 'tictactoe-online-f75da.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg67EP_KfAKn03595HjEiBvvCCMLcDRTs',
    appId: '1:469970791522:ios:ee3fe72743b14c11bef53b',
    messagingSenderId: '469970791522',
    projectId: 'tictactoe-online-f75da',
    storageBucket: 'tictactoe-online-f75da.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOOijkatm-JK4d3avjwVn-_GhlWo7qGCI',
    appId: '1:469970791522:web:a959294d1d4c7cd8bef53b',
    messagingSenderId: '469970791522',
    projectId: 'tictactoe-online-f75da',
    authDomain: 'tictactoe-online-f75da.firebaseapp.com',
    storageBucket: 'tictactoe-online-f75da.firebasestorage.app',
  );
}
